# Generated by Django 5.1.7 on 2025-10-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_migraineprediction_weather_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='daily_notification_limit',
            field=models.IntegerField(default=1, help_text='Maximum migraine alert emails per day for this location (0 = disabled)'),
        ),
    ]
