# Generated by Django on 2025-10-30
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forecast', '0003_location_daily_notification_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('prior_conditions', models.TextField(blank=True, help_text='Optional: List prior health issues relevant to migraines')),
                ('sensitivity_overall', models.FloatField(default=1.0, help_text='Overall sensitivity multiplier (0.5 = less sensitive, 1 = average, 2 = very sensitive)')),
                ('sensitivity_temperature', models.FloatField(default=1.0)),
                ('sensitivity_humidity', models.FloatField(default=1.0)),
                ('sensitivity_pressure', models.FloatField(default=1.0)),
                ('sensitivity_cloud_cover', models.FloatField(default=1.0)),
                ('sensitivity_precipitation', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='auth.user')),
            ],
        ),
    ]
