# Generated by Django 5.2.6 on 2025-10-30 23:40

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_alter_userhealthprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(blank=True, default=dict, null=True)),
                ('response_api_raw', models.JSONField(blank=True, default=dict, null=True)),
                ('response_parsed', models.JSONField(blank=True, default=dict, null=True)),
                ('probability_level', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('analysis_text', models.TextField(blank=True)),
                ('prevention_tips', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_responses', to='forecast.location')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_responses', to='forecast.migraineprediction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
