# Generated by Django 5.2.6 on 2025-10-31 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_llmresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinusitisPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_time', models.DateTimeField(auto_now_add=True)),
                ('target_time_start', models.DateTimeField()),
                ('target_time_end', models.DateTimeField()),
                ('probability', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('weather_factors', models.JSONField(blank=True, default=dict, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinusitis_predictions', to='forecast.weatherforecast')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinusitis_predictions', to='forecast.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinusitis_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
