# Generated by Django 5.2.6 on 2025-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_alter_llmresponse_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.IntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True, help_text='Enable or disable LLM predictions')),
                ('base_url', models.CharField(default='http://192.168.0.11:11434', help_text='Base URL for the LLM API (OpenAI-compatible endpoint)', max_length=500)),
                ('model', models.CharField(default='ibm/granite4:3b-h', help_text='Model name to use for predictions', max_length=200)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key for authentication (leave empty if not required)', max_length=500)),
                ('timeout', models.FloatField(default=240.0, help_text='Request timeout in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configuration',
            },
        ),
    ]
