# Generated by Django 5.2.6 on 2025-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_llmconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable email notifications for migraine and sinusitis alerts'),
        ),
    ]
