# Generated by Django 5.2.6 on 2025-10-31 13:27

import django.utils.timezone
from django.db import migrations, models


def set_existing_config_active(apps, schema_editor):
    """Set the existing configuration as active."""
    LLMConfiguration = apps.get_model('forecast', 'LLMConfiguration')
    # Set the first (and should be only) existing config as active
    config = LLMConfiguration.objects.first()
    if config:
        config.is_active = True
        config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0011_add_prediction_service_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmconfiguration',
            options={'verbose_name': 'LLM Configuration', 'verbose_name_plural': 'LLM Configurations'},
        ),
        migrations.RemoveField(
            model_name='llmconfiguration',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='llmconfiguration',
            name='singleton_id',
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set this configuration as the active one (only one can be active at a time)'),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='name',
            field=models.CharField(default='Default', help_text='Unique name for this LLM configuration', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='llmconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_llm_config'),
        ),
        # Set existing configuration as active
        migrations.RunPython(set_existing_config_active, reverse_code=migrations.RunPython.noop),
    ]
