# Generated by Django 5.2.6 on 2025-11-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0012_alter_llmconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="daily_notification_limit",
            field=models.IntegerField(
                default=1, help_text="Maximum health alert emails per day for this user (0 = disabled)"
            ),
        ),
    ]
