# Generated by Django 5.2.6 on 2025-11-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0013_add_daily_notification_limit_to_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="daily_notification_limit",
        ),
    ]
