# Generated by Django 5.2.6 on 2025-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0014_remove_daily_notification_limit_from_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="notification_frequency_hours",
            field=models.IntegerField(
                default=3,
                help_text="Minimum hours between notifications (default: 3 hours). Prevents notification spam.",
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="prediction_window_end_hours",
            field=models.IntegerField(
                default=6, help_text="End of prediction time window in hours ahead (default: 6 hours)"
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="prediction_window_start_hours",
            field=models.IntegerField(
                default=3, help_text="Start of prediction time window in hours ahead (default: 3 hours)"
            ),
        ),
    ]
