# Generated by Django 5.2.6 on 2025-11-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0015_add_notification_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="daily_migraine_notification_limit",
            field=models.IntegerField(
                default=1, help_text="Maximum migraine alert emails per day (0 = use general limit)"
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="daily_sinusitis_notification_limit",
            field=models.IntegerField(
                default=1, help_text="Maximum sinusitis alert emails per day (0 = use general limit)"
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="digest_time",
            field=models.TimeField(
                blank=True, help_text="Time to send daily digest email (e.g., 08:00 for 8 AM)", null=True
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="last_migraine_notification_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last migraine notification sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="last_notification_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last notification sent to this user", null=True
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="last_sinusitis_notification_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last sinusitis notification sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="notification_mode",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "Immediate - Send alerts as they occur"),
                    ("DIGEST", "Daily Digest - Send one summary email per day"),
                ],
                default="IMMEDIATE",
                help_text="How to deliver notifications",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="notification_severity_threshold",
            field=models.CharField(
                choices=[("MEDIUM", "Medium and High"), ("HIGH", "High only")],
                default="MEDIUM",
                help_text="Only send notifications for predictions at or above this severity level",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="quiet_hours_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable quiet hours to prevent notifications during specific times"
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="quiet_hours_end",
            field=models.TimeField(blank=True, help_text="End of quiet hours (e.g., 07:00 for 7 AM)", null=True),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="quiet_hours_start",
            field=models.TimeField(blank=True, help_text="Start of quiet hours (e.g., 22:00 for 10 PM)", null=True),
        ),
        migrations.CreateModel(
            name="LocationNotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable or disable notifications for this specific location"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority level for this location (1=low, 5=high). Higher priority locations are included first if limits apply.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="forecast.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Notification Preference",
                "verbose_name_plural": "Location Notification Preferences",
                "unique_together": {("user", "location")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("migraine", "Migraine Alert"),
                            ("sinusitis", "Sinusitis Alert"),
                            ("combined", "Combined Alert"),
                            ("digest", "Daily Digest"),
                            ("test", "Test Email"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push Notification")],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("recipient", models.CharField(help_text="Email address, phone number, or device ID", max_length=255)),
                (
                    "severity_level",
                    models.CharField(blank=True, help_text="Highest severity in this notification", max_length=10),
                ),
                ("locations_count", models.IntegerField(default=0, help_text="Number of locations included")),
                ("predictions_count", models.IntegerField(default=0, help_text="Total number of predictions included")),
                (
                    "scheduled_time",
                    models.DateTimeField(blank=True, help_text="When notification was scheduled to be sent", null=True),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="When notification was actually sent", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if sending failed")),
                ("retry_count", models.IntegerField(default=0, help_text="Number of retry attempts")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata about the notification", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "migraine_predictions",
                    models.ManyToManyField(
                        blank=True, related_name="notification_logs", to="forecast.migraineprediction"
                    ),
                ),
                (
                    "sinusitis_predictions",
                    models.ManyToManyField(
                        blank=True, related_name="notification_logs", to="forecast.sinusitisprediction"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at", "user"], name="forecast_no_created_572f97_idx"),
                    models.Index(fields=["status", "notification_type"], name="forecast_no_status_4400f7_idx"),
                ],
            },
        ),
    ]
