# Generated by Django 5.2.6 on 2025-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0016_userhealthprofile_daily_migraine_notification_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("el", "Ελληνικά")],
                default="en",
                help_text="Preferred language for the user interface and notifications",
                max_length=10,
            ),
        ),
    ]
