# Generated by Django 5.2.6 on 2025-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0017_userhealthprofile_language"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="weatherforecast",
            constraint=models.UniqueConstraint(fields=("location", "target_time"), name="unique_location_target_time"),
        ),
    ]
