# Generated by Django 5.2.6 on 2025-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0019_add_high_token_budget_to_llmconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfiguration",
            name="confidence_threshold",
            field=models.FloatField(
                default=0.8,
                help_text="Minimum confidence level (0-1) required to accept LLM classification. Predictions below this threshold are downgraded by one level (e.g., HIGH→MEDIUM).",
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="confidence_adjusted",
            field=models.BooleanField(
                default=False, help_text="Whether the probability level was downgraded due to low confidence"
            ),
        ),
        migrations.AddField(
            model_name="llmresponse",
            name="original_probability_level",
            field=models.CharField(
                blank=True, help_text="Original LLM classification before confidence-based adjustment", max_length=10
            ),
        ),
    ]
