# Generated by Django 5.2.6 on 2025-11-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0020_add_confidence_threshold_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmconfiguration",
            name="extra_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra payload parameters to merge with LLM requests (e.g., temperature, top_p, max_tokens). These will override default values if there are conflicts.",
            ),
        ),
    ]
