# Generated by Django 5.2.6 on 2025-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0021_add_extra_payload_to_llmconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="ui_version",
            field=models.CharField(
                choices=[("v1", "Classic UI"), ("v2", "Modern UI")],
                default="v2",
                help_text="User interface version preference",
                max_length=10,
            ),
        ),
    ]
