# Generated by Django 5.2.6 on 2025-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0022_add_ui_version_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light Mode"), ("dark", "Dark Mode")],
                default="light",
                help_text="Color theme preference (light or dark mode)",
                max_length=10,
            ),
        ),
    ]
