# Generated by Django 5.2.6 on 2025-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0023_add_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="sensitivity_preset",
            field=models.CharField(
                choices=[
                    ("LOW", "Low - Less sensitive to weather changes"),
                    ("NORMAL", "Normal - Average sensitivity"),
                    ("HIGH", "High - More sensitive to weather changes"),
                ],
                default="NORMAL",
                help_text="Your sensitivity to weather changes (passed directly to the prediction model)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userhealthprofile",
            name="sensitivity_overall",
            field=models.FloatField(default=1.0, help_text="DEPRECATED: Use sensitivity_preset instead"),
        ),
    ]
