# Generated by Django 5.2.6 on 2025-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0024_add_sensitivity_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="IANA timezone name (e.g., 'America/New_York', 'Europe/Athens'). Used for digest scheduling.",
                max_length=50,
            ),
        ),
    ]
