# Generated by Django 5.2.6 on 2025-12-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0025_add_location_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmresponse",
            name="inference_time",
            field=models.FloatField(blank=True, help_text="LLM inference time in seconds", null=True),
        ),
    ]
