# Generated by Django 5.2.6 on 2026-04-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0026_add_inference_time_to_llmresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="sensitivity_cloud_cover",
        ),
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="sensitivity_humidity",
        ),
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="sensitivity_overall",
        ),
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="sensitivity_precipitation",
        ),
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="sensitivity_pressure",
        ),
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="sensitivity_temperature",
        ),
    ]
