# Generated by Django 5.2.6 on 2026-04-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0027_remove_deprecated_sensitivity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="daily_hay_fever_notification_limit",
            field=models.IntegerField(
                default=1, help_text="Maximum hay fever alert emails per day (0 = use general limit)"
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="hay_fever_predictions_enabled",
            field=models.BooleanField(default=True, help_text="Enable or disable hay fever predictions for this user"),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="last_hay_fever_notification_sent_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last hay fever notification sent", null=True
            ),
        ),
        migrations.CreateModel(
            name="AirQualityForecast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("forecast_time", models.DateTimeField(help_text="When the forecast was made")),
                ("target_time", models.DateTimeField(help_text="When the forecast is for")),
                ("alder_pollen", models.FloatField(blank=True, null=True)),
                ("birch_pollen", models.FloatField(blank=True, null=True)),
                ("grass_pollen", models.FloatField(blank=True, null=True)),
                ("mugwort_pollen", models.FloatField(blank=True, null=True)),
                ("olive_pollen", models.FloatField(blank=True, null=True)),
                ("ragweed_pollen", models.FloatField(blank=True, null=True)),
                ("pm10", models.FloatField(blank=True, null=True)),
                ("pm2_5", models.FloatField(blank=True, null=True)),
                ("ozone", models.FloatField(blank=True, null=True)),
                ("nitrogen_dioxide", models.FloatField(blank=True, null=True)),
                ("dust", models.FloatField(blank=True, null=True)),
                ("uv_index", models.FloatField(blank=True, null=True)),
                ("european_aqi", models.FloatField(blank=True, null=True)),
                ("us_aqi", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="air_quality_forecasts",
                        to="forecast.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["location", "target_time"], name="forecast_ai_locatio_242161_idx"),
                    models.Index(fields=["target_time"], name="forecast_ai_target__bab0e3_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("location", "target_time"), name="unique_aq_location_target_time")
                ],
            },
        ),
    ]
