# Generated by Django 5.2.6 on 2026-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0029_alter_llmresponse_prediction_type_hayfeverprediction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="hayfever_predictions",
            field=models.ManyToManyField(
                blank=True, related_name="notification_logs", to="forecast.hayfeverprediction"
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("migraine", "Migraine Alert"),
                    ("sinusitis", "Sinusitis Alert"),
                    ("hayfever", "Hay Fever Alert"),
                    ("combined", "Combined Alert"),
                    ("digest", "Daily Digest"),
                    ("test", "Test Email"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
