# Generated by Django 5.2.6 on 2026-04-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0030_add_hayfever_to_notificationlog"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="weatherforecast",
            index=models.Index(fields=["location", "target_time"], name="forecast_we_locatio_8e7a9e_idx"),
        ),
        migrations.AddIndex(
            model_name="weatherforecast",
            index=models.Index(fields=["target_time"], name="forecast_we_target__a92e25_idx"),
        ),
    ]
