# Generated by Django 5.2.6 on 2026-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0032_location_label_optional_place_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhealthprofile",
            name="ui_version",
        ),
    ]
