# Generated by Django 5.2.13 on 2026-08-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0033_remove_userhealthprofile_ui_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthprofile",
            name="email_detail_level",
            field=models.CharField(
                choices=[
                    ("BRIEF", "Brief - Risk level, location and time window only"),
                    ("FULL", "Full - Include weather data, contributing factors and prevention tips"),
                ],
                default="BRIEF",
                help_text="How much detail to include in alert emails",
                max_length=10,
            ),
        ),
    ]
